In [1]:
from sklearn.cluster import KMeans 
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
#写入数据
data=pd.read_csv('D:\data analayse\python\last testing\ProjectC\CarPrice_Assignment.csv')
train_x=data.drop(['CarName','car_ID'],axis=1)
train_x

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [3]:
#将部分值改成数字，调用labelencoder
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
#批量改数据
train_x['fueltype']=le.fit_transform(train_x['fueltype'])
train_x['aspiration']=le.fit_transform(train_x['aspiration'])
train_x['doornumber']=le.fit_transform(train_x['doornumber'])
train_x['carbody']=le.fit_transform(train_x['carbody'])
train_x['drivewheel']=le.fit_transform(train_x['drivewheel'])
train_x['enginelocation']=le.fit_transform(train_x['enginelocation'])
train_x['enginetype']=le.fit_transform(train_x['enginetype'])
train_x['cylindernumber']=le.fit_transform(train_x['cylindernumber'])
train_x['fuelsystem']=le.fit_transform(train_x['fuelsystem'])
train_x.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,0,1,2,2,0,94.5,171.2,65.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,1,0,0,3,1,0,99.8,176.6,66.2,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,1,0,0,3,0,0,99.4,176.6,66.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
#规范数据到0.1之间
min_mx_scaler=preprocessing.MinMaxScaler()
train_x=min_mx_scaler.fit_transform(train_x)
pd.DataFrame(train_x).to_csv('temp.csv',index=False)
train_x

array([[1.        , 1.        , 0.        , ..., 0.22222222, 0.28947368,
        0.20795889],
       [1.        , 1.        , 0.        , ..., 0.22222222, 0.28947368,
        0.28255797],
       [0.6       , 1.        , 0.        , ..., 0.16666667, 0.26315789,
        0.28255797],
       ...,
       [0.2       , 1.        , 0.        , ..., 0.13888889, 0.18421053,
        0.40631051],
       [0.2       , 0.        , 1.        , ..., 0.36111111, 0.28947368,
        0.43076312],
       [0.2       , 1.        , 1.        , ..., 0.16666667, 0.23684211,
        0.43461099]])

In [1]:
#手肘法算K的取值范围
import matplotlib.pyplot as plt
sse = []
for k in range(1, 100):
	# kmeans算法
	kmeans = KMeans(n_clusters=k)
	kmeans.fit(train_x)
	# 计算inertia簇内误差平方和
	sse.append(kmeans.inertia_)
x = range(1, 50)
plt.xlabel('K')
plt.ylabel('SSE')
plt.plot(x, sse, 'o-')
plt.show()
print(sse)
#k= 7 为最佳值

NameError: name 'KMeans' is not defined

In [6]:
# Kmeans 聚类
kmeans=KMeans(n_clusters=7)
#训练
kmeans.fit(train_x)
#预测结果
predict_x=kmeans.predict(train_x)
print(predict_x)
print(train_x)

[0 0 0 1 1 0 5 5 5 4 0 5 0 5 5 5 0 5 6 6 1 6 6 4 1 1 1 4 1 4 6 6 6 6 6 1 1
 6 6 1 1 1 6 1 6 1 0 5 5 0 6 6 6 1 1 0 0 0 0 6 1 6 1 2 1 5 2 3 3 3 3 5 0 5
 0 4 6 6 6 4 4 6 4 4 4 1 1 4 1 6 2 6 1 1 6 6 1 1 6 1 1 5 5 5 0 4 0 5 3 5 3
 5 3 5 3 5 3 5 6 4 1 1 1 1 4 0 0 0 0 0 1 0 0 5 0 5 4 4 6 6 6 1 1 1 1 4 1 1
 1 4 6 6 1 1 1 1 1 1 2 2 1 1 1 6 6 0 0 0 0 0 0 0 0 1 3 1 1 1 0 0 5 5 2 6 2
 1 1 3 1 0 0 5 3 1 5 5 5 5 5 5 5 5 5 3 5]
[[1.         1.         0.         ... 0.22222222 0.28947368 0.20795889]
 [1.         1.         0.         ... 0.22222222 0.28947368 0.28255797]
 [0.6        1.         0.         ... 0.16666667 0.26315789 0.28255797]
 ...
 [0.2        1.         0.         ... 0.13888889 0.18421053 0.40631051]
 [0.2        0.         1.         ... 0.36111111 0.28947368 0.43076312]
 [0.2        1.         1.         ... 0.16666667 0.23684211 0.43461099]]

In [29]:
#合并聚类结果，插入到原数据
data['labels']=predict_x
result=data.sort_values("labels",ascending=False)
result.head()
result.to_csv("D:\\data analayse\\python\\last testing\\ProjectC\\car_data121.csv",encoding="gbk")

In [27]:
#找到VW的车型，并返回类别
show=pd.read_csv("D:\data analayse\python\last testing\ProjectC\car_data121.csv",encoding="gbk")
show.head()
DEG=show.loc[show['CarName'].str.contains('vw')|show['CarName'].str.contains('volkswagen')]
DEG['labels'].unique()

array([6, 5, 3, 2, 1, 0], dtype=int64)

In [18]:
#筛选出只有VW的类型的数据并生成新的数据
answer=show.loc[~(show['labels']==4)]
answer.sort_values(by='labels',ascending=False)

,Unnamed: 0,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,labels
0,31,32,2,honda civic cvcc,gas,std,two,hatchback,fwd,front,...,1bbl,2.91,3.410,9.2,76,6000,31,38,6855.0,6
19,78,79,2,mitsubishi outlander,gas,std,two,hatchback,fwd,front,...,2bbl,2.97,3.230,9.4,68,5500,31,38,6669.0,6
21,76,77,2,mitsubishi mirage,gas,std,two,hatchback,fwd,front,...,2bbl,2.97,3.230,9.4,68,5500,37,41,5389.0,6
22,59,60,1,mazda 626,gas,std,two,hatchback,fwd,front,...,2bbl,3.39,3.390,8.6,84,4800,26,32,8845.0,6
23,118,119,1,plymouth fury iii,gas,std,two,hatchback,fwd,front,...,2bbl,2.97,3.230,9.4,68,5500,37,41,5572.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,58,59,3,mazda glc 4,gas,std,two,hatchback,rwd,front,...,mpfi,3.33,3.255,9.4,135,6000,16,23,15645.0,0
181,74,75,1,buick regal sport coupe (turbo),gas,std,two,hardtop,rwd,front,...,mpfi,3.80,3.350,8.0,184,4500,14,16,45400.0,0
182,57,58,3,mazda rx-7 gs,gas,std,two,hatchback,rwd,front,...,4bbl,3.33,3.255,9.4,101,6000,17,23,13645.0,0
183,56,57,3,mazda glc,gas,std,two,hatchback,rwd,front,...,4bbl,3.33,3.255,9.4,101,6000,17,23,11845.0,0
204,0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,...,mpfi,3.47,2.680,9.0,111,5000,21,27,13495.0,0

In [21]:
#导出数据
answer.to_csv("D:\\data analayse\\python\\last testing\\ProjectC\\answer.csv",encoding="gbk")